doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    namespace: DoctrineMigrations
    organize_migrations: BY_YEAR
    custom_template: "%kernel.project_dir%/src/Migrations/migration.tpl"
