fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%mail_box%'
        sender_name: '%mail_from%'
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true