hwi_oauth:
    fosub:
        username_iterations: 30
        properties:
            google: googleId
            mailru: mailruId
            yandex: yandexId
            vkontakte: vkontakteId
            facebook: facebookId
    firewall_name: [main]
    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        google:
            type:                google
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               'email profile'
        vkontakte:
            type:                vkontakte
            client_id:           '%env(VK_ID)%'
            client_secret:       '%env(VK_SECRET)%'
            scope:               'email status'
        mailru:
            type:                mailru
            client_id:           '%env(MAILRU_ID)%'
            client_secret:       '%env(MAILRU_SECRET)%'
        yandex:
            type:                yandex
            client_id:           '%env(YA_ID)%'
            client_secret:       '%env(YA_SECRET)%'
        facebook:
            type:                facebook
            client_secret:       '%env(FB_SECRET)%'
            client_id:           '%env(FB_ID)%'
            scope:               'email'
            options:
                display: popup #dialog is optimized for popup window
                auth_type: rerequest # Re-asking for Declined Permissions