security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_MODERATOR:   ROLE_MODERATOR # moderator is only moderator. he can't use application as user
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATOR]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        hwi_oauth.user.provider:
            id: hwi_oauth.user.provider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true
            logout_on_user_change: true
            oauth:
                resource_owners:
                    google: google_login
                    vkontakte: vk_login
                    mailru: mailru_login
                    yandex: yandex_login
                    facebook: facebook_login
                login_path: /login
#                use_forward:       false
#                failure_path:      /login
#                default_target_path: after_login
                provider: hwi_oauth.user.provider
                oauth_user_provider:
                    service: App\Security\FOSUBUserProvider

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/cashback, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
