sonata_admin:
    title: 'Sonata Admin'
    templates:
        layout: 'admin/standart_layout.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            sonata.group.users:
                label:  'Пользователи'
                icon:   '<i class="fa fa-user"></i>'
                items:
                    - sonata.user
            sonata.group.cashback:
                label: 'Кешбэки'
                icon:   '<i class="fa fa-money"></i>'
                items:
                    - sonata.cashback_platform
                    - sonata.cashback
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    sonata.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Пользователи' }
    sonata.cashback_platform:
        class: App\Admin\CashBackPlatformAdmin
        arguments: [~, App\Entity\CashBackPlatform, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Источники кешбеков' }
    sonata.cashback:
        class: App\Admin\CashBackAdmin
        arguments: [~, App\Entity\CashBack, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Кешбэк программы' }