sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            sonata.group.users:
                label:  'Пользователи'
                icon:   '<i class="fa fa-user"></i>'
                items:
                    - sonata.user
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

services:
    sonata.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Пользователи' }