version: '2'

services:
    php:
        build: ./config/docker/php
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
        env_file:
          - .env
        environment: #Variables does not extract for another variable from ^
            DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
        entrypoint:
          - "./config/docker/php/docker-entrypoint.sh"
    nginx:
        image: 4xxi/nginx:flex
        ports:
            - 8080:80
        volumes:
            - ./config/docker/nginx/symfony.prod.conf:/etc/nginx/sites-available/symfony.prod.conf
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: mariadb:10.1
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
volumes:
    vendor:
    db:
#TODO копирование шареных папок вместо линкования(var/sessions, public/static??)
