version: '3.2'

services:
    php:
        build: ./config/docker/php
        volumes:
            - .:/var/www/html
            - trash:/var/www/
        expose:
            - "9000"
        environment:
          - PARENT_USER_ID
          - APP_ENV
        entrypoint:
          - "./config/docker/php/docker-entrypoint.sh"
    nginx:
        image: 4xxi/nginx:flex
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - ./config/docker/nginx/symfony.conf:/etc/nginx/sites-available/symfony.conf
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    db:
        image: mariadb:10.1
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PROMPT_COMMAND: 'history -a'
            HISTTIMEFORMAT: '%h %d %H:%M:%S '
            HISTFILESIZE: 20000
            HISTFILE: '/var/lib/mysql/bash_history_db'
            MYSQL_HISTFILE: '/var/lib/mysql/bash_history_db_mysql'
    db_test:
        image: mariadb:10.1
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
volumes:
    db:
    trash:
