monolog:
    channels: ['api']
    handlers:
        filter_for_errors:
            type: fingers_crossed
            action_level: error
            handler: papertrail
            channels: ['!event', '!api']
            excluded_http_codes: [404, 403, 401, 400]
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 10
        papertrail:
            type: socket
            connection_string: '%env(LOGGER_PATH)%'
        api:
            type: rotating_file
            path: "%kernel.logs_dir%/api_%kernel.environment%_.log"
            level: info
            channels: ['api']
            max_files: 10
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
