monolog:
    handlers:
        main:
            type: stream
            action_level: error
            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
#        nested:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: error
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
