monolog:
    handlers:
        filter_for_errors:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            max_files: 10
        parpetrail:
            action_level: error
            type: socket
            connection_string: '%env(LOGGER_PATH)%'
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
