#Redefinded default route after registration first step
fos_user_registration_check_email:
    path: /

google_login:
    path: /login/google
google_connect:
    path: /connect/google
vk_login:
    path: /login/vkontakte
vk_connect:
    path: /connect/vkontakte
mailru_login:
    path: /login/mailru
mailru_connect:
    path: /connect/mailru
yandex_login:
    path: /login/yandex
yandex_connect:
    path: /connect/yandex
facebook_login:
    path: /login/facebook
facebook_connect:
    path: /connect/facebook